spring:
  application:
    name: StiflixBackend
  config:
    import: optional:file:.env[.properties]
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1d
logging:
  level:
    org.springframework.web: DEBUG